### ISSUE TITLE
v1.1 Release

### ISSUE THREAD

**Issue by akuma06** [NyaaPantsu/NyaaPantsu-android-app#17]
Here is the discussion on what should we add for v1.1.
For now we have:

- [x] Possibility to watch anime from the app #5 (Added by #6 )
- [x] Swipe to refresh #7 (Added by #16 )
- [x] Restructuration of code (Added by #6 , #14 )

**Comment by xdk78** [comment]
IMO that's enough for 1.1

**Comment by akuma06** [comment]
Thought too also
