### ISSUE TITLE
v1.2 Release

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#53]
- [x] Cleanup code / Fix minor code issues #23
- [x] Add - Next/Previous on Swipe gesture  https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/19
- [x] Add - RecyclerView Adapter instead BaseAdapter https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/24
- [x] Fix - Streaming issues https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/29 
- [x] Fix - Images won't load in description https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/30 
- [x] Add - Ability to select multiple languages https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/31
- [x] Add magnet upload in the upload form https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/32
- [x] Add Make website link clickable https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/33
- [x] Add Possibility to interact with cardview by swipe left https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/34
- [x] Fix Better way display network image https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/37
- [x] Update api to 1.1.1 https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/46
- [x] Add user profile like on website https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/36
- [x] Make nyaa pantsu voice play https://github.com/NyaaPantsu/NyaaPantsu-android-app/issues/44
- [x] Improve translation #62 
- [x] Android O support #63

@akuma06 
@xdk78
@ltype

**Comment by akuma06** [comment]
#23 Can it be closed?
#44 we need to wait for it

And does someone have tested the upload? Like I just saw that the language input was not displaying. Would like if someone else test it on his device to be sure it works

**Comment by xdk78** [comment]
BIG RELEASE

**Comment by akuma06** [comment]
I never talked about it here but the version naming in Pantsu (for every software) should follow this pattern (was decided a while ago):
* They should all have a link with "Pantsu"
* They have to follow the Gojuon alphabetical order (https://en.wikipedia.org/wiki/Gojūon)


Every suggestion is welcome. For now the only suggestion for this version is: Iroppoi Pantsu (which means Sexy Pantsu). We are at "I" since the A was done with "Aoi Pantsu"

**Comment by yiiTT** [comment]
> Iroppoi Pantsu

![img](http://i.imgur.com/M21uw27.png)

**Comment by akuma06** [comment]
@xdk78 or @ltype Can one of you publish the "v1.2" tag with "git command"? I can't do it now :') Don't forget to name the version "Iroppoi Pantsu"

Edit: Delayed to improve translation

**Comment by xdk78** [comment]
Wait m8

**Comment by xdk78** [comment]
Let me translate some strings and and "support" for Android 0

**Comment by akuma06** [comment]
No problem, I will add a new issue to keep track

**Comment by ltype** [comment]
I published new realease with v1.2
